### ISSUE TITLE
Promocodes error in laravel 5.1

### ISSUE THREAD

**Issue by balaji-inn** [zgabievi/laravel-promocodes#11]
Promocodes error in Laravel Vertion 5.1

**Following the README.md file instruction installation**
after the i  created the controller and put the code **Promocodes::output($amount = 1)**. 
 it gives me error. but i tried in laravel version 5.2 it's works

**FatalErrorException in Promocodes.php line 30:
Call to a member function toArray() on string**

**Comment by zgabievi** [comment]
Hello @balaji-inn ,

From Laravel 5.2 `lists` method changed and was named `pluck`, I'm using the last one, because it's supported on latest versions of Laravel. I've released version [0.5.1](https://github.com/zgabievi/laravel-promocodes/tree/0.5.1), and you can use it in you Laravel 5.1 project.

You will need to require this package like this: `composer require zgabievi/promocodes:0.5.1`

Let me know if you will face some problems.

**Comment by Balajibhema** [comment]
Hi,
Now it's fixed. Thanks
