### ISSUE TITLE
Use case for additional data

### ISSUE THREAD

**Issue by keatwei** [zgabievi/laravel-promocodes#22]
array $data = []
May I know whats the use case for additional data and what it use to store?

**Comment by zgabievi** [comment]
@keatwei thank you for the question.

This is where you can read about the usage of [additional data](https://github.com/zgabievi/laravel-promocodes#how-to-use-additional-data)

And use case would be:
If I want to store some data with promo code. And use it when redeemed. For Example, If we have 80% discount on Black Friday, and we want to tell the user that he used code that discounted 80% and it's because of Black Friday. So we can store data: `reason => "Black Friday"`, and when redeemed we can access this data
